from . import profile
from . import start
from . import help
from . import premium
from . import chatroom
from . import admin
from . import Personaldata
from . import otherhandlers
from . import mainhandler
from . import echo
